ASCII_file_specs:
  data_separator: "\t"
  data_start: 22
  header_lines: 21
  measurement_description: 21
  measurement_regex: '[^\t]+|\t(?=\t)|\t$'
  units_regex: '[^\t]+|\t(?=\t)|\t$'
Analysis:
- brown_preanalysis
Files:
- S:/Testing/Irradiation Studies/Pre-Production/34253/037_RINSC/Strips/34253_037_PSS_XX_HM_IrradSensor_AfterAlibava_Interstrip.txt
- S:/Testing/Irradiation Studies/Pre-Production/34253/037_RINSC/Strips/34253_037_PSS_XX_HM_IrradSensor_BeforeAlibava_Interstrip.txt
Filetype: ASCII
IVCV_QTC:
  1C2:
    PlotLabel: CV CURVES - Full depletion
    PlotOptions:
      gridstyle:
        grid_line_color: black
        grid_line_width: 1.5
        minor_xgrid_line_color: lightgray
        minor_ygrid_line_color: lightgray
        xgrid_line_dash:
        - 4
        - 4
        ygrid_line_dash:
        - 10
        - 4
      invert_xaxis: false
      invert_yaxis: false
      logx: false
      logy: false
      padding: !!python/tuple
      - 0
      - 0.1
      shared_axes: false
      show_grid: true
      ylabel: 1/c^2 [arb. units]
      ylim: !!python/tuple
      - 0
      - 0.08
  BoxWhiskerOptions:
    box_alpha: 0.3
    height: 1500
    shared_axes: false
    width: 2600
  CV:
    PlotLabel: CV CURVES
    PlotOptions:
      gridstyle:
        grid_line_color: black
        grid_line_width: 1.5
        minor_xgrid_line_color: lightgray
        minor_ygrid_line_color: lightgray
        xgrid_line_dash:
        - 4
        - 4
        ygrid_line_dash:
        - 10
        - 4
      invert_xaxis: false
      invert_yaxis: false
      logx: false
      logy: false
      padding: !!python/tuple
      - 0
      - 0.1
      shared_axes: false
      show_grid: true
      ylabel: capacitance [nF]
    UnitConversion: nano
  CVQValue:
    PlotLabel: Q-Value CV measurement
    PlotOptions:
      gridstyle:
        grid_line_color: black
        grid_line_width: 1.5
        minor_xgrid_line_color: lightgray
        minor_ygrid_line_color: lightgray
        xgrid_line_dash:
        - 4
        - 4
        ygrid_line_dash:
        - 10
        - 4
      padding: !!python/tuple
      - 0
      - 0.1
      shared_axes: false
      show_grid: true
      xformatter: '%.0f'
      yformatter: '%.0f'
    ToolsOptions:
      yaxisENG: true
    UnitConversion: mega
  DoSpecialPlots:
  - BoxWhisker
  General:
    fontsize:
      labels: 24
      legend: 11
      title: 28
      xticks: 24
      yticks: 24
    height: 800
    responsive: false
    shared_axes: false
    width: 1200
  IV:
    AdditionalPlots:
    - BoxWhisker
    PlotLabel: IV CURVES
    PlotOptions:
      gridstyle:
        grid_line_color: black
        grid_line_width: 1.5
        minor_xgrid_line_color: lightgray
        minor_ygrid_line_color: lightgray
        xgrid_line_dash:
        - 4
        - 4
        ygrid_line_dash:
        - 10
        - 4
      invert_xaxis: false
      invert_yaxis: false
      logx: false
      logy: true
      padding: !!python/tuple
      - 0
      - 0.1
      shared_axes: false
      show_grid: true
      xformatter: '%.0f'
      yformatter: '%.0f'
      ylabel: current [nA]
    ToolsOptions:
      yaxisENG: true
    UnitConversion: nano
  Layout:
    cols: 1
  humidity:
    AdditionalPlots:
    - BoxWhisker
    PlotLabel: Humidity
    PlotOptions:
      show_grid: false
  temperature:
    AdditionalPlots:
    - BoxWhisker
    PlotLabel: Temperature
    PlotOptions:
      show_grid: false
Output: S:/Testing/Irradiation Studies/Pre-Production/34253/037_RINSC/CVIV/IrradSensor
  Plots
Stripscan:
  AirT:
    PlotLabel: Air Temperature
    PlotOptions:
      show_grid: false
      xlabel: Pad [#]
      ylabel: Temperature [deg]
  BoxWhiskerOptions:
    box_alpha: 0.3
    height: 1200
    shared_axes: false
    width: 1200
  Cac:
    AdditionalPlots:
    - concatHistogram
    PlotLabel: Coupling Capacitance
    PlotOptions:
      gridstyle:
        grid_line_color: black
        grid_line_width: 1.5
        minor_xgrid_line_color: lightgray
        minor_ygrid_line_color: lightgray
        xgrid_line_dash:
        - 4
        - 4
        ygrid_line_dash:
        - 10
        - 4
      padding: !!python/tuple
      - 0.1
      - 0.1
      show_grid: true
      xlabel: Pad [#]
      ylim: !!python/tuple
      - 6.0e-11
      - 1.0e-10
    PlotStyles:
    - Curve
  Cint:
    AdditionalPlots:
    - concatHistogram
    PlotLabel: Interstrip Capacitance
    PlotOptions:
      gridstyle:
        grid_line_color: black
        grid_line_width: 1.5
        minor_xgrid_line_color: lightgray
        minor_ygrid_line_color: lightgray
        xgrid_line_dash:
        - 4
        - 4
        ygrid_line_dash:
        - 10
        - 4
      padding: !!python/tuple
      - 0.1
      - 0.1
      show_grid: true
      xlabel: Pad [#]
    PlotStyles:
    - Curve
    UnitConversion: pico
  DoSpecialPlots:
  - concatHistogram
  - Violin
  - BoxWhisker
  General:
    fontsize:
      labels: 24
      legend: 11
      title: 28
      xticks: 24
      yticks: 24
    height: 700
    padding: !!python/tuple
    - 0
    - 0.1
    responsive: false
    shared_axes: false
    width: 1200
  HistogramOptions:
    alpha: 0.6
    shared_axes: false
  Humidity:
    PlotLabel: Humidity
    PlotOptions:
      show_grid: false
      xlabel: Pad [#]
      ylabel: Humidity [rel%]
  Idark:
    AdditionalPlots:
    - concatHistogram
    PlotLabel: Total Sensor Current
    PlotOptions:
      gridstyle:
        grid_line_color: black
        grid_line_width: 1.5
        minor_xgrid_line_color: lightgray
        minor_ygrid_line_color: lightgray
        xgrid_line_dash:
        - 4
        - 4
        ygrid_line_dash:
        - 10
        - 4
      padding: !!python/tuple
      - 0.1
      - 0.1
      show_grid: true
      xlabel: Pad [#]
    PlotStyles:
    - Curve
    UnitConversion: micro
  Idiel:
    AdditionalPlots:
    - concatHistogram
    PlotLabel: Pinhole Current
    PlotOptions:
      gridstyle:
        grid_line_color: black
        grid_line_width: 1.5
        minor_xgrid_line_color: lightgray
        minor_ygrid_line_color: lightgray
        xgrid_line_dash:
        - 4
        - 4
        ygrid_line_dash:
        - 10
        - 4
      logy: true
      padding: !!python/tuple
      - 0.1
      - 0.1
      show_grid: true
      xlabel: Pad [#]
    PlotStyles:
    - Curve
  Istrip:
    AdditionalPlots:
    - concatHistogram
    PlotLabel: Strip Currents
    PlotOptions:
      gridstyle:
        grid_line_color: black
        grid_line_width: 1.5
        minor_xgrid_line_color: lightgray
        minor_ygrid_line_color: lightgray
        xgrid_line_dash:
        - 4
        - 4
        ygrid_line_dash:
        - 10
        - 4
      padding: !!python/tuple
      - 0.1
      - 0.1
      show_grid: true
      xlabel: Pad [#]
    PlotStyles:
    - Curve
  IstripNbr:
    AdditionalPlots:
    - concatHistogram
    PlotLabel: Strip Currents Nbr
    PlotOptions:
      gridstyle:
        grid_line_color: black
        grid_line_width: 1.5
        minor_xgrid_line_color: lightgray
        minor_ygrid_line_color: lightgray
        xgrid_line_dash:
        - 4
        - 4
        ygrid_line_dash:
        - 10
        - 4
      padding: !!python/tuple
      - 0.1
      - 0.1
      show_grid: true
      xlabel: Pad [#]
    PlotStyles:
    - Curve
    UnitConversion: nano
  Layout:
    cols: 1
  Measurement_aliases:
    ChuckT: Temperature
    Coupling Cap: Cac
    Global Current: Idark
    Interstrip C: Cint
    IstripNbr_Median: IstripNbr
    Istrip_Median: Istrip
    Pinhole: Idiel
    RH: Humidity
    Strip: Pad
  Rint:
    AdditionalPlots:
    - concatHistogram
    PlotLabel: Interstrip Resistance
    PlotOptions:
      gridstyle:
        grid_line_color: black
        grid_line_width: 1.5
        minor_xgrid_line_color: lightgray
        minor_ygrid_line_color: lightgray
        xgrid_line_dash:
        - 4
        - 4
        ygrid_line_dash:
        - 10
        - 4
      padding: !!python/tuple
      - 0.1
      - 0.1
      show_grid: true
      xlabel: Pad [#]
    PlotStyles:
    - Curve
    UnitConversion: giga
  Rpoly:
    AdditionalPlots:
    - concatHistogram
    PlotLabel: Poly-Silicon Resistor Resitance
    PlotOptions:
      gridstyle:
        grid_line_color: black
        grid_line_width: 1.5
        minor_xgrid_line_color: lightgray
        minor_ygrid_line_color: lightgray
        xgrid_line_dash:
        - 4
        - 4
        ygrid_line_dash:
        - 10
        - 4
      padding: !!python/tuple
      - 0.1
      - 0.1
      show_grid: true
      xlabel: Pad [#]
    PlotStyles:
    - Curve
  RpolyNbr:
    AdditionalPlots:
    - concatHistogram
    PlotLabel: Poly-Silicon Resistor Resitance Nbr
    PlotOptions:
      gridstyle:
        grid_line_color: black
        grid_line_width: 1.5
        minor_xgrid_line_color: lightgray
        minor_ygrid_line_color: lightgray
        xgrid_line_dash:
        - 4
        - 4
        ygrid_line_dash:
        - 10
        - 4
      padding: !!python/tuple
      - 0.1
      - 0.1
      show_grid: true
      xlabel: Pad [#]
      ylim: !!python/tuple
      - 0
      - 3.0
    PlotStyles:
    - Curve
    UnitConversion: mega
  Temperature:
    PlotLabel: Temperature
    PlotOptions:
      show_grid: false
      xlabel: Pad [#]
      ylabel: Temperature [deg]
  ViolinOptions:
    box_alpha: 0.3
    height: 1200
    shared_axes: false
    width: 1200
backend: bokeh
bad_strip_detection:
  Config:
    Cac:
    - 1.4e-10
    - - 120e-12
      - 160e-12
    - 5
    Capfactor: 1.5
    Cint:
    - 7.0e-13
    - - 3.0e-13
      - 5e-12
    - 5
    HighIstrip: 3
    HighRpoly: 3.0
    Humidity:
    - 22
    - - 18
      - 27
    - 10
    Idark:
    - 5e-6
    - - -500e-9
      - -150e-9
    - 5.0
    Idiel:
    - 1e-12
    - - -5.0e-10
      - 5.0e-10
    - 20
    IdielThresholdCurrent: 5.0e-10
    Istrip:
    - -100e-12
    - - -200e-12
      - 0
    - 20
    IstripNbr:
    - -100e-12
    - - -200e-12
      - 0
    - 20
    Istripfactor: 3
    LMSsize: 50
    LowCap: 0.8
    MeasStripvsTotal: 1.3
    Rint:
    - 100e9
    - - 50e9
      - 1e12
    - 50.0
    Rpoly:
    - 1500000
    - - 1200000
      - 1800000
    - 5
    RpolyNbr:
    - 1500000
    - - 1200000
      - 1800000
    - 5
    Rpolyfactor: 3
    Temperature:
    - 23
    - - 20
      - 23
    - 2
    atol: 0
    fit_cluster_size: 10
    maximumCapOutliner: 30
    outlier_std: 3
    quantile: 0.95
    remove_outliner: true
    rtol: 0.35
  General:
    fontsize:
      labels: 24
      legend: 11
      title: 28
      xticks: 24
      yticks: 24
    height: 1000
    width: 1500
  Layout:
    cols: 1
  Measurement_aliases:
    ChuckT: Temperature
    Coupling Cap: Cac
    Global Current: Idark
    Interstrip C: Cint
    Median: Istrip
    MedianNbr: IstripNbr
    Pinhole: Idiel
    RH: Humidity
    Rbias: Rpoly
    Strip: Pad
  do_holoviews_table: true
file_order:
- 34253_037_PSS_XX_HM_IrradSensor_AfterAlibava_Interstrip
- 34253_037_PSS_XX_HM_IrradSensor_BeforeAlibava_Interstrip
